import { useState, useEffect } from 'react'
import { ArrowRight, Clock3, Plus, Sparkles, Stars } from 'lucide-react'
import './HomePage.css'

const EXAMPLES = [
  'The Future of Renewable Energy',
  'AI in Healthcare',
  'Startup Pitch Deck',
  'Digital Marketing Strategy',
]

export default function HomePage({ onNew, onPreview, loading }) {
  const [history, setHistory] = useState([])

  useEffect(() => {
    fetch('/history')
      .then(r => r.json())
      .then(data => setHistory(data))
      .catch(console.error)
  }, [])

  return (
    <div className="home">
      <header className="home-header">
        <div className="home-logo">
          <span className="logo-mark">JA</span>
          <span>JahnaviAI</span>
        </div>
        <div className="home-header-badge">Presentation studio</div>
      </header>

      <main className="home-main">
        <section className="hero-shell">
          <div className="hero-copy">
            <div className="eyebrow"><Stars size={14} /> Black studio interface</div>
            <h1 className="hero-title">Build polished presentations with a single prompt.</h1>
            <p className="hero-sub">
              Generate a complete deck, preview it in a professional dark workspace, and export a finished PowerPoint in one flow.
            </p>

            <div className="hero-actions">
              <button className="btn-create" onClick={() => onNew()} disabled={loading}>
                {loading ? <><span className="spinner-dark" /> Generating…</> : <><Sparkles size={16} /> Create presentation</>}
              </button>
              <div className="hero-note"><Clock3 size={14} /> Typical deck: 6 to 10 slides</div>
            </div>
          </div>

          <div className="hero-panel">
            <div className="hero-panel-top">
              <span>Quick start</span>
              <ArrowRight size={14} />
            </div>
            <div className="hero-panel-grid">
              <div className="panel-card">
                <span className="panel-kicker">Topic</span>
                <strong>AI, finance, health, education, strategy</strong>
              </div>
              <div className="panel-card">
                <span className="panel-kicker">Output</span>
                <strong>Theme-aware slides with export-ready layout</strong>
              </div>
              <div className="panel-card panel-card-accent">
                <span className="panel-kicker">Mode</span>
                <strong>Dark, calm, editorial presentation system</strong>
              </div>
            </div>
          </div>
        </section>

        <section className="home-section">
          <div className="section-head">
            <p className="examples-label">Try an example</p>
            <span className="section-hint">Use one of these as a starting prompt</span>
          </div>
          <div className="examples-grid">
            {EXAMPLES.map(ex => (
              <button key={ex} className="example-chip" onClick={() => onNew(ex)}>
                <Plus size={13} /> {ex}
              </button>
            ))}
          </div>
        </section>

        {history.length > 0 && (
          <section className="home-section home-history">
            <div className="section-head history-head">
              <div>
                <p className="examples-label">Recent work</p>
                <h2>Your previous presentations</h2>
              </div>
              <span className="section-hint">Open a deck to inspect or export it again</span>
            </div>
            <div className="history-grid">
              {history.map((item, idx) => (
                <button
                  key={idx}
                  type="button"
                  className="history-card"
                  onClick={() => onPreview(item)}
                >
                  <div className="history-card-top">
                    <span className="history-index">{String(idx + 1).padStart(2, '0')}</span>
                    <span className="history-slides">{item.slides?.length || 0} slides</span>
                  </div>
                  <div className="history-title">{item.title || 'Untitled Presentation'}</div>
                  <div className="history-subtitle">{item.subtitle || 'Generated by AI'}</div>
                  <div className="history-footer">Open deck</div>
                </button>
              ))}
            </div>
          </section>
        )}
      </main>
    </div>
  )
}
